name: Laravel + Vue CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  backend:

    name: Laravel Backend
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: Backend
        
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.5"
          extensions: mbstring, pdo_mysql, bcmath, ctype, fileinfo, json, openssl, tokenizer, xml
          coverage: none

      - name: Install Composer Dependencies
        run: composer install --prefer-dist --no-progress --no-interaction

      - name: Set Directory Permissions
        run: chmod -R 775 storage bootstrap/cache

  frontend:

    name: Vue Frontend
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: Frontend

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
          cache-dependency-path: Frontend/package-lock.json

      - name: Install Dependencies
        run: npm install

      - name: Build Vue Application
        run: npm run build

      # Uncomment if using Vitest
      # - name: Run Vue Tests
      #   run: npm run test
